// Originally generated by rlpgen, since MAINTAINED BY HAND.
//
// Do not re-run rlpgen over this file without re-applying the trailing-optional
// logic below: the Header carries optional fields that rlpgen's older output did
// not model correctly (see the comment on the optional block).

//go:build !norlpgen
// +build !norlpgen

package types

import "github.com/ethereum/go-ethereum/common"
import "github.com/ethereum/go-ethereum/rlp"
import "io"

func (obj *Header) EncodeRLP(_w io.Writer) error {
	w := rlp.NewEncoderBuffer(_w)
	_tmp0 := w.List()
	w.WriteBytes(obj.ParentHash[:])
	w.WriteBytes(obj.UncleHash[:])
	w.WriteBytes(obj.Coinbase[:])
	w.WriteBytes(obj.Root[:])
	w.WriteBytes(obj.TxHash[:])
	w.WriteBytes(obj.ReceiptHash[:])
	w.WriteBytes(obj.Bloom[:])
	if obj.Difficulty == nil {
		w.Write(rlp.EmptyString)
	} else {
		if obj.Difficulty.Sign() == -1 {
			return rlp.ErrNegativeBigInt
		}
		w.WriteBigInt(obj.Difficulty)
	}
	if obj.Number == nil {
		w.Write(rlp.EmptyString)
	} else {
		if obj.Number.Sign() == -1 {
			return rlp.ErrNegativeBigInt
		}
		w.WriteBigInt(obj.Number)
	}
	w.WriteUint64(obj.GasLimit)
	w.WriteUint64(obj.GasUsed)
	w.WriteUint64(obj.Time)
	w.WriteBytes(obj.Extra)
	w.WriteBytes(obj.MixDigest[:])
	w.WriteBytes(obj.Nonce[:])

	// Trailing optional fields, in struct order: BaseFee, the EIP-7594 PeerDAS
	// group, then AttestationsHash.
	//
	// RLP may only omit a trailing optional field when that field AND every field
	// after it is zero. So the highest field actually set decides how many are
	// written, and any earlier optional must be emitted (as its zero value) to
	// keep positions aligned — decoding is reflection-based off the struct tags
	// and matches purely on order.
	//
	// This is why activating AttestationsHash must be fork-gated: switching it on
	// also starts encoding the PeerDAS group, changing the header encoding for
	// every node at once.
	var (
		hasAttestations = obj.AttestationsHash != (common.Hash{})
		hasPeerDAS      = obj.ShardCount > 0 || obj.DataShardCount > 0 ||
			obj.DataRoot != (common.Hash{}) || obj.BlobHash != (common.Hash{})
		hasBaseFee = obj.BaseFee != nil
	)
	if hasAttestations {
		hasPeerDAS = true
	}
	if hasPeerDAS {
		hasBaseFee = true
	}

	if hasBaseFee {
		if obj.BaseFee == nil {
			w.Write(rlp.EmptyString)
		} else {
			if obj.BaseFee.Sign() == -1 {
				return rlp.ErrNegativeBigInt
			}
			w.WriteBigInt(obj.BaseFee)
		}
	}
	if hasPeerDAS {
		w.WriteBytes(obj.DataRoot[:])
		w.WriteBytes(obj.BlobHash[:])
		w.WriteUint64(obj.ShardCount)
		w.WriteUint64(obj.DataShardCount)
	}
	if hasAttestations {
		w.WriteBytes(obj.AttestationsHash[:])
	}

	w.ListEnd(_tmp0)
	return w.Flush()
}
